Feature/update communication functions
Software-Engineering-Bachelor-Project/mycroft pull request #153
Opened 2020-04-15 12:23 UTC by Kal-Elx

Closes #149

2020-04-15 12:53 UTC, Kal-Elx commented
Closes #147

2020-04-15 14:07 UTC, Flodklumpen requested changes
Looks good. Just small linting-stuff.
file: model_serializers.py
line: 2
Not supposed to be more than one import on one line. 
line: 14
Should be two blank lines.

2020-04-15 14:13 UTC, SteBry commented on backend/test/test_integration/test_file_manager.py
> +class GetSourceFolders(TestCase):
Add one test case for when no folders exist and one for several rootfolders

2020-04-15 14:15 UTC, SteBry commented on backend/test/test_integration/test_file_manager.py
> +class GetSourceFolders(TestCase):
Otherwise it looks good!

2020-04-16 07:44 UTC, Flodklumpen approved these changes

2020-04-16 07:45 UTC, merged